import Head from "next/head";
import { table, minifyRecords } from "./api/utils/Airtable";

export default function Home(initialProducts) {
  console.log(initialProducts);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const products = await table.select({}).firstPage();

    return {
      props: {
        initialProducts: minifyRecords(products),
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        err: "Something went bad",
      },
    };
  }
}
