name: Trigger cron API route
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the cron API route
        run: |
          curl --request POST \
          --url 'https://qotqot-git-cron-comicscrip.vercel.app/api/cron?key=123'